### ISSUE TITLE
Install instructions for Mac

### ISSUE THREAD

**Issue by PieterT2000** [Rahel-A/gvm_lights#1]
It would be really great if you could add installation instructions for MacOS. How does one find out the MAC address of the GVM light? I've tried using the ARP protocol but not sure what IP network is used by the lamp. My guess is 192.168.4.1?

**Comment by Rahel-A** [comment]
Docker should also be available on MacOS, see install instructions here:
https://docs.docker.com/desktop/install/mac-install/
Check README for specific environment values needed.
I've also added a feature that should allow the server to automatically find the relevant GVM lights in proximity to the server, just make sure you don't set `APP_CLIENTS`.
